#ifndef EI_HTTP_DOCS_H
#define EI_HTTP_DOCS_H

static const char EI_ROOT_JSON[] =
    "{\"name\":\"quixiembed\",\"status\":\"ok\","
    "\"docs\":\"/docs\",\"openapi\":\"/openapi.json\","
    "\"health\":\"/healthz\",\"routes\":["
    "\"GET /api/tags\",\"POST /api/embed\"]}\n";

static const char EI_HEALTH_JSON[] = "{\"status\":\"ok\"}\n";

static const char EI_DOCS_HTML[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>quixiembed API</title>\n"
    "<style>\n"
    ":root{color-scheme:light dark;--bg:#f7f7f5;--surface:#fff;--text:#18181b;"
    "--muted:#5f6368;--line:#d9d9d4;--link:#075985;--get:#166534;--post:#9a3412;"
    "--code:#f0f0ec}*{box-sizing:border-box}body{margin:0;background:var(--bg);"
    "color:var(--text);font:15px/1.55 system-ui,-apple-system,BlinkMacSystemFont,"
    "\"Segoe UI\",sans-serif;letter-spacing:0}header{background:var(--surface);"
    "border-bottom:1px solid var(--line)}.wrap{width:min(920px,calc(100% - 32px));"
    "margin:auto}header .wrap{padding:40px 0 30px}.eyebrow{margin:0 0 6px;"
    "font:700 12px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}"
    "h1{margin:0;font-size:32px;line-height:1.2;letter-spacing:0}header p{max-width:680px;"
    "margin:12px 0 0;color:var(--muted)}nav{display:flex;gap:18px;margin-top:20px}"
    "a{color:var(--link)}main{padding:8px 0 48px}section{padding:28px 0;"
    "border-bottom:1px solid var(--line)}section:last-child{border-bottom:0}"
    "h2{display:flex;align-items:center;gap:10px;margin:0 0 14px;font-size:20px;"
    "letter-spacing:0}.method{display:inline-block;padding:2px 7px;border:1px solid;"
    "border-radius:4px;font:700 12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}"
    ".get{color:var(--get)}.post{color:var(--post)}code,pre{font-family:"
    "ui-monospace,SFMono-Regular,Menlo,monospace}code{background:var(--code);"
    "padding:2px 4px;border-radius:3px}pre{overflow:auto;margin:14px 0 0;padding:16px;"
    "background:#202124;color:#f8f8f2;border-radius:6px;font-size:13px;line-height:1.5}"
    "table{width:100%;border-collapse:collapse;margin-top:14px}th,td{padding:9px 10px;"
    "border:1px solid var(--line);text-align:left;vertical-align:top}th{background:"
    "var(--surface)}@media(prefers-color-scheme:dark){:root{--bg:#141414;"
    "--surface:#1d1d1d;--text:#f4f4f5;--muted:#a1a1aa;--line:#3f3f46;"
    "--link:#7dd3fc;--get:#86efac;--post:#fdba74;--code:#292929}}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<header><div class=\"wrap\"><p class=\"eyebrow\">LOCAL EMBEDDING INFERENCE</p>"
    "<h1>quixiembed API</h1><p>HTTP interface for EmbeddingGemma with 768, 512, "
    "256, and 128-dimensional Matryoshka outputs.</p><nav>"
    "<a href=\"/openapi.json\">OpenAPI JSON</a><a href=\"/healthz\">Health</a>"
    "</nav></div></header>\n"
    "<main class=\"wrap\">\n"
    "<section><h2><span class=\"method get\">GET</span><code>/healthz</code></h2>"
    "<p>Returns HTTP 200 after the model and inference workspace are ready.</p>"
    "<pre>{\"status\":\"ok\"}</pre></section>\n"
    "<section><h2><span class=\"method get\">GET</span><code>/api/tags</code></h2>"
    "<p>Lists the model exposed by this server.</p>"
    "<pre>{\"models\":[{\"name\":\"embeddinggemma-300m\"}]}</pre></section>\n"
    "<section><h2><span class=\"method post\">POST</span><code>/api/embed</code></h2>"
    "<p>Embeds one string or an array of strings. Text is processed exactly as "
    "provided.</p><table><thead><tr><th>Field</th><th>Type</th><th>Contract</th></tr>"
    "</thead><tbody><tr><td><code>input</code></td><td>string or string[]</td>"
    "<td>Required; array limit defaults to 32</td></tr><tr><td><code>model</code></td>"
    "<td>string</td><td>Optional compatibility field</td></tr><tr>"
    "<td><code>dimensions</code></td><td>integer</td><td>768, 512, 256, or 128; "
    "default 768</td></tr><tr><td><code>encoding_format</code></td><td>string</td>"
    "<td><code>float</code> or <code>base64</code>; default float</td></tr>"
    "</tbody></table><pre>curl -sS http://127.0.0.1:42666/api/embed \\\n"
    "  -H 'Content-Type: application/json' \\\n"
    "  -d '{\"input\":[\"search_query: what powers the cell\"],"
    "\"dimensions\":256}'</pre><pre>{\"embeddings\":[[0.0123, -0.0456, ...]]}</pre>"
    "</section>\n"
    "</main>\n"
    "</body>\n"
    "</html>\n";

static const char EI_OPENAPI_JSON[] =
    "{"
    "\"openapi\":\"3.1.0\","
    "\"info\":{\"title\":\"quixiembed API\",\"version\":\"1.0.0\","
    "\"description\":\"Local EmbeddingGemma inference API.\"},"
    "\"servers\":[{\"url\":\"http://127.0.0.1:42666\"}],"
    "\"paths\":{"
    "\"/\":{\"get\":{\"summary\":\"Service discovery\",\"responses\":{"
    "\"200\":{\"description\":\"Service metadata\",\"content\":{"
    "\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Service\"}}}}}}},"
    "\"/docs\":{\"get\":{\"summary\":\"Human-readable API documentation\","
    "\"responses\":{\"200\":{\"description\":\"HTML documentation\"}}}},"
    "\"/openapi.json\":{\"get\":{\"summary\":\"OpenAPI document\","
    "\"responses\":{\"200\":{\"description\":\"OpenAPI 3.1 document\"}}}},"
    "\"/healthz\":{\"get\":{\"summary\":\"Readiness check\",\"responses\":{"
    "\"200\":{\"description\":\"Model is ready\",\"content\":{"
    "\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Health\"}}}}}}},"
    "\"/api/tags\":{\"get\":{\"summary\":\"List served models\",\"responses\":{"
    "\"200\":{\"description\":\"Model list\",\"content\":{\"application/json\":{"
    "\"schema\":{\"$ref\":\"#/components/schemas/TagsResponse\"}}}}}}},"
    "\"/api/embed\":{\"post\":{\"summary\":\"Create embeddings\","
    "\"requestBody\":{\"required\":true,\"content\":{\"application/json\":{"
    "\"schema\":{\"$ref\":\"#/components/schemas/EmbedRequest\"}}}},"
    "\"responses\":{\"200\":{\"description\":\"Embedding vectors\",\"content\":{"
    "\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/EmbedResponse\"}}}},"
    "\"400\":{\"description\":\"Invalid request\",\"content\":{\"application/json\":{"
    "\"schema\":{\"$ref\":\"#/components/schemas/Error\"}}}}}}}},"
    "\"components\":{\"schemas\":{"
    "\"Service\":{\"type\":\"object\",\"required\":[\"name\",\"status\",\"docs\","
    "\"openapi\",\"health\",\"routes\"],\"properties\":{"
    "\"name\":{\"type\":\"string\"},\"status\":{\"type\":\"string\"},"
    "\"docs\":{\"type\":\"string\"},\"openapi\":{\"type\":\"string\"},"
    "\"health\":{\"type\":\"string\"},\"routes\":{\"type\":\"array\","
    "\"items\":{\"type\":\"string\"}}}},"
    "\"Health\":{\"type\":\"object\",\"required\":[\"status\"],\"properties\":{"
    "\"status\":{\"type\":\"string\",\"const\":\"ok\"}}},"
    "\"TagsResponse\":{\"type\":\"object\",\"required\":[\"models\"],\"properties\":{"
    "\"models\":{\"type\":\"array\",\"items\":{\"type\":\"object\","
    "\"required\":[\"name\"],\"properties\":{\"name\":{\"type\":\"string\"}}}}}},"
    "\"EmbedRequest\":{\"type\":\"object\",\"required\":[\"input\"],\"properties\":{"
    "\"model\":{\"type\":\"string\"},\"input\":{\"oneOf\":[{\"type\":\"string\"},"
    "{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"minItems\":1,"
    "\"maxItems\":32}]},\"dimensions\":{\"type\":\"integer\","
    "\"enum\":[768,512,256,128],\"default\":768},\"encoding_format\":{"
    "\"type\":\"string\",\"enum\":[\"float\",\"base64\"],\"default\":\"float\"}}},"
    "\"EmbedResponse\":{\"type\":\"object\",\"required\":[\"embeddings\"],"
    "\"properties\":{\"embeddings\":{\"type\":\"array\",\"items\":{\"oneOf\":[{"
    "\"type\":\"array\",\"items\":{\"type\":\"number\",\"format\":\"float\"}},{"
    "\"type\":\"string\",\"contentEncoding\":\"base64\"}]}}}},"
    "\"Error\":{\"type\":\"object\",\"required\":[\"error\"],\"properties\":{"
    "\"error\":{\"type\":\"string\"}}}"
    "}}"
    "}\n";

#endif
